### ISSUE TITLE
Run the SRL model on the preprocessed ACE dataset

### ISSUE THREAD

**Issue by gabrer** [veronica320/Zeroshot-Event-Extraction#2]
I have preprocessed the ACE dataset and obtained the output files with a format consistent with the sample file provided.

However, it is not clear to me whether this format is ready to be used as input into the SRL model linked, or it needs to be modified. If so, what part/script of the SRL model would you suggest using?

Also, did you train/fine-tune the SRL model on the ACE dataset or just run a trained SRL model (which one?) directly on them?

Many thanks!

**Comment by veronica320** [comment]
Hi @gabrer, thanks for your interest! In the experiments of our paper, I used a group-internal request API to access the SRL model, but since it's hosted on our servers, it's unlikely to be publicly available. Instead, our group released the Github repo of the SRL model so people can run it themselves. 

Sorry that I don't have direct experience in running the Github version! I'll try to provide as much info as I could though. What I've used in our paper is a verb SRL and a nominal SRL model, which correspond to the "SRL_VERB" and the "SRL_NOM_ALL" under ["The folders and views"](https://github.com/CogComp/SRL-English#the-folders-and-views). In terms of the input format, it says: 

> To predict: Create input text file with JSON formatting: {"sentence": "This is a sentence."} for each sentence that you would like predicted. 

In case there's anything else unclear, I would suggest raising an issue under the SRL repo. Sorry about the inconvenience :)

For your second question, I didn't train SRL models on ACE but used the "SRL_VERB" and the "SRL_NOM_ALL" views directly.
